INSERT INTO contents (id, filename, original_name, url, relative_path, content_type, size, context, entity_type, entity_id, content_order, is_primary, content_category, title, description, alt, metadata, is_public, download_count, file_hash, tenant_id, created_at, updated_at, created_by, updated_by, is_active)
VALUES
(1, 'apple.jpg', 'apple.jpg', 'http://localhost:8086/api/images/tanzeem/product/apple.jpg', '/images/tanzeem/product/apple.jpg', 'image/jpeg', 52480, 'product', 'Product', 1, 1, true, 'IMAGE', 'Apple Product Image', 'Fresh red apples', 'Fresh red apples product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_apple_001', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true),

(2, 'banana.jpg', 'banana.jpg', 'http://localhost:8086/api/images/tanzeem/product/banana.jpg', '/images/tanzeem/product/banana.jpg', 'image/jpeg', 48320, 'product', 'Product', 2, 1, true, 'IMAGE', 'Banana Product Image', 'Fresh yellow bananas', 'Fresh yellow bananas product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_banana_002', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true),

(3, 'carrot.jpg', 'carrot.jpg', 'http://localhost:8086/api/images/tanzeem/product/carrot.jpg', '/images/tanzeem/product/carrot.jpg', 'image/jpeg', 45760, 'product', 'Product', 3, 1, true, 'IMAGE', 'Carrot Product Image', 'Fresh orange carrots', 'Fresh orange carrots product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_carrot_003', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true),

(4, 'milk.jpg', 'milk.jpg', 'http://localhost:8086/api/images/tanzeem/product/milk.jpg', '/images/tanzeem/product/milk.jpg', 'image/jpeg', 41280, 'product', 'Product', 4, 1, true, 'IMAGE', 'Milk Product Image', 'Fresh dairy milk', 'Fresh dairy milk product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_milk_004', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true),

(5, 'bread.jpg', 'bread.jpg', 'http://localhost:8086/api/images/tanzeem/product/bread.jpg', '/images/tanzeem/product/bread.jpg', 'image/jpeg', 54720, 'product', 'Product', 5, 1, true, 'IMAGE', 'Bread Product Image', 'Fresh baked bread', 'Fresh baked bread product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_bread_005', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true),

(6, 'orange-juice.jpg', 'orange-juice.jpg', 'http://localhost:8086/api/images/tanzeem/product/orange-juice.jpg', '/images/tanzeem/product/orange-juice.jpg', 'image/jpeg', 38560, 'product', 'Product', 6, 1, true, 'IMAGE', 'Orange Juice Product Image', 'Fresh orange juice', 'Fresh orange juice product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_orange_juice_006', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true),

(7, 'beef.jpg', 'beef.jpg', 'http://localhost:8086/api/images/tanzeem/product/beef.jpg', '/images/tanzeem/product/beef.jpg', 'image/jpeg', 61440, 'product', 'Product', 7, 1, true, 'IMAGE', 'Beef Product Image', 'Fresh beef meat', 'Fresh beef meat product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_beef_007', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true),

(8, 'salmon.jpg', 'salmon.jpg', 'http://localhost:8086/api/images/tanzeem/product/salmon.jpg', '/images/tanzeem/product/salmon.jpg', 'image/jpeg', 57600, 'product', 'Product', 8, 1, true, 'IMAGE', 'Salmon Product Image', 'Fresh salmon fish', 'Fresh salmon fish product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_salmon_008', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true),

(9, 'choco-cake.jpg', 'choco-cake.jpg', 'http://localhost:8086/api/images/tanzeem/product/choco-cake.jpg', '/images/tanzeem/product/choco-cake.jpg', 'image/jpeg', 65280, 'product', 'Product', 9, 1, true, 'IMAGE', 'Chocolate Cake Product Image', 'Delicious chocolate cake', 'Delicious chocolate cake product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_choco_cake_009', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true),

(10, 'black-pepper.jpg', 'black-pepper.jpg', 'http://localhost:8086/api/images/tanzeem/product/black-pepper.jpg', '/images/tanzeem/product/black-pepper.jpg', 'image/jpeg', 42560, 'product', 'Product', 10, 1, true, 'IMAGE', 'Black Pepper Product Image', 'Premium black pepper', 'Premium black pepper product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_black_pepper_010', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true),

(11, 'canned-beans.jpg', 'canned-beans.jpg', 'http://localhost:8086/api/images/tanzeem/product/canned-beans.jpg', '/images/tanzeem/product/canned-beans.jpg', 'image/jpeg', 39680, 'product', 'Product', 11, 1, true, 'IMAGE', 'Canned Beans Product Image', 'Quality canned beans', 'Quality canned beans product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_canned_beans_011', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true),

(12, 'cheddar.jpg', 'cheddar.jpg', 'http://localhost:8086/api/images/tanzeem/product/cheddar.jpg', '/images/tanzeem/product/cheddar.jpg', 'image/jpeg', 51200, 'product', 'Product', 12, 1, true, 'IMAGE', 'Cheddar Cheese Product Image', 'Premium cheddar cheese', 'Premium cheddar cheese product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_cheddar_012', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true),

(13, 'almonds.jpg', 'almonds.jpg', 'http://localhost:8086/api/images/tanzeem/product/almonds.jpg', '/images/tanzeem/product/almonds.jpg', 'image/jpeg', 46080, 'product', 'Product', 13, 1, true, 'IMAGE', 'Roasted Almonds Product Image', 'Premium roasted almonds', 'Premium roasted almonds product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_almonds_013', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true),

(14, 'sardines.jpg', 'sardines.jpg', 'http://localhost:8086/api/images/tanzeem/product/sardines.jpg', '/images/tanzeem/product/sardines.jpg', 'image/jpeg', 44800, 'product', 'Product', 14, 1, true, 'IMAGE', 'Canned Sardines Product Image', 'Quality canned sardines', 'Quality canned sardines product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_sardines_014', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true),

(15, 'olive-oil.jpg', 'olive-oil.jpg', 'http://localhost:8086/api/images/tanzeem/product/olive-oil.jpg', '/images/tanzeem/product/olive-oil.jpg', 'image/jpeg', 40960, 'product', 'Product', 15, 1, true, 'IMAGE', 'Olive Oil Product Image', 'Premium olive oil', 'Premium olive oil product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_olive_oil_015', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true),

(16, 'rice.jpg', 'rice.jpg', 'http://localhost:8086/api/images/tanzeem/product/rice.jpg', '/images/tanzeem/product/rice.jpg', 'image/jpeg', 43520, 'product', 'Product', 16, 1, true, 'IMAGE', 'Egyptian Rice Product Image', 'Quality Egyptian rice', 'Quality Egyptian rice product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_rice_016', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true),

(17, 'pasta.jpg', 'pasta.jpg', 'http://localhost:8086/api/images/tanzeem/product/pasta.jpg', '/images/tanzeem/product/pasta.jpg', 'image/jpeg', 47360, 'product', 'Product', 17, 1, true, 'IMAGE', 'Italian Pasta Product Image', 'Authentic Italian pasta', 'Authentic Italian pasta product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_pasta_017', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true),

(18, 'detergent.jpg', 'detergent.jpg', 'http://localhost:8086/api/images/tanzeem/product/detergent.jpg', '/images/tanzeem/product/detergent.jpg', 'image/jpeg', 49920, 'product', 'Product', 18, 1, true, 'IMAGE', 'Washing Powder Product Image', 'Effective washing powder', 'Effective washing powder product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_detergent_018', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true),

(19, 'baby-shampoo.jpg', 'baby-shampoo.jpg', 'http://localhost:8086/api/images/tanzeem/product/baby-shampoo.jpg', '/images/tanzeem/product/baby-shampoo.jpg', 'image/jpeg', 37120, 'product', 'Product', 19, 1, true, 'IMAGE', 'Baby Shampoo Product Image', 'Gentle baby shampoo', 'Gentle baby shampoo product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_baby_shampoo_019', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true),

(20, 'face-cream.jpg', 'face-cream.jpg', 'http://localhost:8086/api/images/tanzeem/product/face-cream.jpg', '/images/tanzeem/product/face-cream.jpg', 'image/jpeg', 35840, 'product', 'Product', 20, 1, true, 'IMAGE', 'Face Cream Product Image', 'Moisturizing face cream', 'Moisturizing face cream product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_face_cream_020', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true),

(21, 'frozen-fries.jpg', 'frozen-fries.jpg', 'http://localhost:8086/api/images/tanzeem/product/frozen-fries.jpg', '/images/tanzeem/product/frozen-fries.jpg', 'image/jpeg', 53760, 'product', 'Product', 21, 1, true, 'IMAGE', 'Frozen Potatoes Product Image', 'Quality frozen potatoes', 'Quality frozen potatoes product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_frozen_fries_021', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true),

(22, 'frozen-fruits.jpg', 'frozen-fruits.jpg', 'http://localhost:8086/api/images/tanzeem/product/frozen-fruits.jpg', '/images/tanzeem/product/frozen-fruits.jpg', 'image/jpeg', 58880, 'product', 'Product', 22, 1, true, 'IMAGE', 'Frozen Mixed Fruits Product Image', 'Premium frozen mixed fruits', 'Premium frozen mixed fruits product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_frozen_fruits_022', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true),

(23, 'oats.jpg', 'oats.jpg', 'http://localhost:8086/api/images/tanzeem/product/oats.jpg', '/images/tanzeem/product/oats.jpg', 'image/jpeg', 41600, 'product', 'Product', 23, 1, true, 'IMAGE', 'Organic Oats Product Image', 'Premium organic oats', 'Premium organic oats product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_oats_023', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true),

(24, 'detox.jpg', 'detox.jpg', 'http://localhost:8086/api/images/tanzeem/product/detox.jpg', '/images/tanzeem/product/detox.jpg', 'image/jpeg', 36480, 'product', 'Product', 24, 1, true, 'IMAGE', 'Detox Juice Product Image', 'Healthy detox juice', 'Healthy detox juice product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_detox_024', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true),

(25, 'chips.jpg', 'chips.jpg', 'http://localhost:8086/api/images/tanzeem/product/chips.jpg', '/images/tanzeem/product/chips.jpg', 'image/jpeg', 45120, 'product', 'Product', 25, 1, true, 'IMAGE', 'Potato Chips Product Image', 'Crispy potato chips', 'Crispy potato chips product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_chips_025', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true),

(26, 'cookies.jpg', 'cookies.jpg', 'http://localhost:8086/api/images/tanzeem/product/cookies.jpg', '/images/tanzeem/product/cookies.jpg', 'image/jpeg', 50560, 'product', 'Product', 26, 1, true, 'IMAGE', 'Chocolate Cookies Product Image', 'Delicious chocolate cookies', 'Delicious chocolate cookies product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_cookies_026', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true),

(27, 'red-lentils.jpg', 'red-lentils.jpg', 'http://localhost:8086/api/images/tanzeem/product/red-lentils.jpg', '/images/tanzeem/product/red-lentils.jpg', 'image/jpeg', 42240, 'product', 'Product', 27, 1, true, 'IMAGE', 'Red Lentils Product Image', 'Premium red lentils', 'Premium red lentils product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_red_lentils_027', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true),

(28, 'honey.jpg', 'honey.jpg', 'http://localhost:8086/api/images/tanzeem/product/honey.jpg', '/images/tanzeem/product/honey.jpg', 'image/jpeg', 39040, 'product', 'Product', 28, 1, true, 'IMAGE', 'Natural Honey Product Image', 'Pure natural honey', 'Pure natural honey product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_honey_028', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true),

(29, 'peanut-butter.jpg', 'peanut-butter.jpg', 'http://localhost:8086/api/images/tanzeem/product/peanut-butter.jpg', '/images/tanzeem/product/peanut-butter.jpg', 'image/jpeg', 44160, 'product', 'Product', 29, 1, true, 'IMAGE', 'Peanut Butter Product Image', 'Creamy peanut butter', 'Creamy peanut butter product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_peanut_butter_029', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true),

(30, 'sunflower-seeds.jpg', 'sunflower-seeds.jpg', 'http://localhost:8086/api/images/tanzeem/product/sunflower-seeds.jpg', '/images/tanzeem/product/sunflower-seeds.jpg', 'image/jpeg', 47680, 'product', 'Product', 30, 1, true, 'IMAGE', 'Sunflower Seeds Product Image', 'Roasted sunflower seeds', 'Roasted sunflower seeds product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_sunflower_seeds_030', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true),

(31, 'sausages.jpg', 'sausages.jpg', 'http://localhost:8086/api/images/tanzeem/product/sausages.jpg', '/images/tanzeem/product/sausages.jpg', 'image/jpeg', 55040, 'product', 'Product', 31, 1, true, 'IMAGE', 'Canned Sausages Product Image', 'Quality canned sausages', 'Quality canned sausages product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_sausages_031', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true),

(32, 'baby-milk.jpg', 'baby-milk.jpg', 'http://localhost:8086/api/images/tanzeem/product/baby-milk.jpg', '/images/tanzeem/product/baby-milk.jpg', 'image/jpeg', 38720, 'product', 'Product', 32, 1, true, 'IMAGE', 'Baby Milk Product Image', 'Nutritious baby milk formula', 'Nutritious baby milk formula product image', '{"width": 800, "height": 600, "quality": "high"}', true, 0, 'hash_baby_milk_032', 'tanzeem', NOW(), NOW(), 'admin', 'admin', true);