export const LOCATION_ICON_OPTIONS = [
    { title: 'شاحنة', value: 'mdi-truck' },
    { title: 'مصنع', value: 'mdi-factory' },
    { title: 'متجر', value: 'mdi-store' },
    { title: 'مكتب', value: 'mdi-office-building' },
    { title: 'شركة', value: 'mdi-domain' },
    { title: 'مستودع', value: 'mdi-warehouse' },
    { title: 'طائرة', value: 'mdi-airplane' },
    { title: 'سفينة', value: 'mdi-ship-wheel' },
    { title: 'حقيبة عمل', value: 'mdi-briefcase' },
    { title: 'أدوات', value: 'mdi-tools' }
]

export const UNIT_ICON_OPTIONS = [
    { title: 'قطعة', value: 'piece' },
    { title: 'كيلوغرام', value: 'kg' },
    { title: 'غرام', value: 'gram' },
    { title: 'لتر', value: 'liter' },
    { title: 'مليلتر', value: 'ml' },
    { title: 'متر', value: 'meter' },
    { title: 'سنتيمتر', value: 'cm' },
    { title: 'صندوق', value: 'box' },
    { title: 'علبة', value: 'can' },
    { title: 'زجاجة', value: 'bottle' },
    { title: 'كيس', value: 'bag' },
    { title: 'عبوة', value: 'pack' }
]

export const CATEGORY_ICON_OPTIONS = [
    { text: 'أجهزة كمبيوتر', value: 'mdi-laptop' },
    { text: 'هواتف ذكية', value: 'mdi-cellphone' },
    { text: 'أجهزة لوحية', value: 'mdi-tablet' },
    { text: 'كاميرا', value: 'mdi-camera' },
    { text: 'سماعات', value: 'mdi-headphones' },
    { text: 'ساعات ذكية', value: 'mdi-watch' },
    { text: 'ألعاب', value: 'mdi-gamepad-variant' },
    { text: 'مكتبة', value: 'mdi-book-open-variant' },
    { text: 'ملابس', value: 'mdi-tshirt-crew' },
    { text: 'أحذية', value: 'mdi-shoe-formal' },
    { text: 'مجوهرات', value: 'mdi-diamond' },
    { text: 'رياضة', value: 'mdi-basketball' },
    { text: 'منزل وحديقة', value: 'mdi-home' },
    { text: 'طعام ومشروبات', value: 'mdi-food' },
    { text: 'صحة وجمال', value: 'mdi-heart' },
    { text: 'أطفال', value: 'mdi-baby-carriage' },
    { text: 'سيارات', value: 'mdi-car' },
    { text: 'أدوات', value: 'mdi-hammer-screwdriver' },
    { text: 'مكتب', value: 'mdi-briefcase' },
    { text: 'فنون وحرف', value: 'mdi-palette' },
    // إضافات من أصناف SQL
    { text: 'فواكه', value: 'mdi-fruit-cherries' },
    { text: 'خضروات', value: 'mdi-carrot' },
    { text: 'مخبوزات', value: 'mdi-bread-slice' },
    { text: 'مشروبات', value: 'mdi-glass-cocktail' },
    { text: 'ألبان', value: 'mdi-cow' },
    { text: 'لحوم', value: 'mdi-food-steak' },
    { text: 'حلويات', value: 'mdi-cupcake' },
    { text: 'بهارات', value: 'mdi-shaker' },
    { text: 'حبوب', value: 'mdi-seed' },
    { text: 'معلبات', value: 'mdi-food-variant' },
    { text: 'مكسرات', value: 'mdi-peanut' },
    { text: 'معلبات لحوم', value: 'mdi-food-drumstick' },
    { text: 'زيوت ودهون', value: 'mdi-bottle-tonic' },
    { text: 'معكرونة وأرز', value: 'mdi-noodles' },
    { text: 'منتجات تنظيف', value: 'mdi-spray-bottle' },
    { text: 'منتجات أطفال', value: 'mdi-baby-face-outline' },
    { text: 'منتجات تجميل', value: 'mdi-lipstick' },
    { text: 'أطعمة مجمدة', value: 'mdi-snowflake' },
    { text: 'منتجات صحية', value: 'mdi-leaf' },
    { text: 'وجبات خفيفة', value: 'mdi-food' }
]
